### ISSUE TITLE
Final Grade

### ISSUE THREAD

**Issue by jmann-williams** [jmann-williams/ecommerce-pattern-library#14]
### E-commerce/Pattern Library Rationale — @thomasjbradley

My e-commerce website and pattern library fully represented all of the possible components and their variations. I feel it does fully explain everything to someone else. Although the teammate aspect was cut, I still tried to keep that mindset. I tried to keep everything simple and easy to understand so that if anyone was to jump on the project they would have no problem understanding what is going on. All of my patterns have clear descriptions. I did run into an issue fairly late into development with a few patterns (2 cards and sections) where no information was showing and was unable to fix, but it all shows on my website. I really like the concept of the pattern library. I feel it made things a lot easier for me in certain areas.

---
***Style & design* — **3****
My whole pattern library is cohesive and all designs somewhat reflect the brand. I probably could have made the branding look a little more fun to go along with the sock designs. The pages have a consistent style and margin. 

***Patterns* — **2****
I created and used pretty much everything a website would need.

***Explanations* — **3****
Everything is complete, clear, and concise as possible.

***Accessibility* — **1****
My website has very little accessibility and could definitely have more. You are able to tab around, but that is about it.

***Semantics* — **2****
I'm pretty sure I correctly used different HTML tags.

***Responsiveness* — **3****
The website is quite responsive. The product card button has some issues with longer names. Everything else looks pretty good.

***Code Quality* — **2****
I took my time and made sure everything was indented properly but everything could be way more accessible.

***Git & commits* — **3****
My Git commits were clear and concise. Everything has described the changes accurately.

---
**19/24 —  79%**

**Comment by thomasjbradley** [comment]
Your website is designed so nicely, cleanly & clearly. Thanks for putting in the effort to learn and apply the material this term.
