### ISSUE TITLE
Marks For - Multiple Assignments

### ISSUE THREAD

**Issue by jmann-williams** [jmann-williams/ecommerce-pattern-library#2]
### **COMPLETED ASSIGNMENTS @thomasjbradley:**

**ASSIGNMENTS:** 
- **sharing code with layouts**
- **preparing product data**
- **building pages with patterns** -- _not everything applied to my website_
- **jekyll generators**

**THE LEFTOVERS:**
- **typography + colors** -- _previously did but saw it was not marked_
- **images + cards** -- _previously did but saw it was not marked_

**Comment by thomasjbradley** [comment]
The “Tyopgraphy & colours” isn’t complete. The `<a>` tags aren’t styled & neither are the `<mark>` tags.
