### ISSUE TITLE
Homepage product cards images and information not showing

### ISSUE THREAD

**Issue by jmann-williams** [jmann-williams/ecommerce-pattern-library#3]
@thomasjbradley
 
My cards (product, category, and collection) are not reading the markdown file and displaying the images and descriptions. Right now I have all cards the same, and then I will have them changed later.

**Comment by thomasjbradley** [comment]
Try changing all of these to `include.data` instead of `page.data`:
https://github.com/jmann-williams/ecommerce-pattern-library/blob/master/_patterns/cards/product-card.html#L2

**Comment by jmann-williams** [comment]
@thomasjbradley 

I tried that, but it didn't work.

**Comment by thomasjbradley** [comment]
Commit & push?

**Comment by jmann-williams** [comment]
@thomasjbradley I updated it

**Comment by thomasjbradley** [comment]
Seems to be working on the `/products` page now. But the title still isn’t working.
https://github.com/jmann-williams/ecommerce-pattern-library/blob/master/_patterns/cards/product-card.html#L4

It’s missing the `.data`—`{{include.data.name}}`—also notice that you called it “name” in the MD files.

**Comment by jmann-williams** [comment]
@thomasjbradley That fixed the issue of it in the pattern library, but it still isn't showing up on the actual homepage

**Comment by thomasjbradley** [comment]
I’d do this kind of code on the homepage, like the for-loop, but intermix it with the `<div>` `.grid` & `.unit` stuff:
https://github.com/jmann-williams/ecommerce-pattern-library/blob/master/products.html#L8-L10

**Comment by jmann-williams** [comment]
@thomasjbradley 

I got the product cards to show up. How would I pick and choose which/how many cards I want to display?

**Comment by thomasjbradley** [comment]
Picking & choosing is a little difficult. But you can do random very easily & you can limit the number that show up easily.

*Limiting—*
https://github.com/jmann-williams/ecommerce-pattern-library/blob/master/index.html#L12
```
{% for product in site.products limit:3 %}
```

See how I’ve added `limit:3` into the loop.

---

*Random—*
https://github.com/jmann-williams/ecommerce-pattern-library/blob/master/index.html#L12
```
{% assign random_products=site.products|sample:3 %}
{% for product in random_products %}
```

I had to add a new line above the loop that chooses a random sample, in this case 3 random products. Then the loop changes to point to the random products.

---

*Choosing—*
Which choosing you cannot use the for-loop—no `{% for %}`. It would be more like this:

```
{% assign product=site.products[3] %}
{% pattern cards/product-card data=product %}
```

The 3 above denotes product number 3, or Markdown file number 3—but remember that counting starts at 0, so it’s the fourth alphabetical Markdown file.

**Comment by jmann-williams** [comment]
@thomasjbradley Got it. Thanks!
