### ISSUE TITLE
Marks For Multiple Assignments

### ISSUE THREAD

**Issue by jmann-williams** [jmann-williams/ecommerce-pattern-library#4]
### COMPLETED ASSIGNMENTS: @thomasjbradley:

**ASSIGNMENTS:**
- homepage template
- finalizing doc patterns
- product listing page template

**THE LEFTOVERS:**
- typography + colors

### QUESTION:
- For the product detail page, do I need to create a separate HTML file for each product?

**Comment by thomasjbradley** [comment]
Nope—you only need to edit one single file: `_layouts/products.html`. That layout will be used for every, single product on the website.
